project: "neuroprobe-baseline"
model: "resnet18"
dataset: "CIFAR10"
seed: 42
device: "cuda"
training:
  epochs: 5
  batch_size: 128
  lr: 0.001
  optimizer: "adam"
  weight_decay: 0.0001

save_dir: "experiments/baseline"

wandb:
  project: "neuroprobe-baseline"
  run_name: "resnet18-cifar10-baseline"
